# Generated by Django 6.0.5 on 2026-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_team_options_alter_matchevent_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_half_added_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half_added_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player_out',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
