# Generated by Django 6.0.5 on 2026-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_first_half_added_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalty_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalty_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
