# Generated by Django 6.0.5 on 2026-08-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_away_penalty_score_match_home_penalty_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='postponed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='postponement_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('postponed', 'Postponed'), ('finished', 'Finished')], default='upcoming', max_length=20),
        ),
    ]
