# Generated by Django 6.0.5 on 2026-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_postponed_at_match_postponement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
