# Generated by Django 6.0.5 on 2026-08-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('sub', 'Substitution'), ('foul', 'Foul'), ('corner', 'Corner')], max_length=20),
        ),
    ]
