# Generated by Django 6.0.5 on 2026-08-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.CharField(choices=[('not_started', 'Not started'), ('first_half', 'First half'), ('half_time', 'Half time'), ('second_half', 'Second half'), ('full_time', 'Full time')], default='not_started', max_length=20),
        ),
    ]
