# Generated by Django 6.0.5 on 2026-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clock_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
