# Generated by Django 6.0.5 on 2026-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_clock_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='period',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('first_half', 'First half'), ('half_time', 'Half time'), ('second_half', 'Second half'), ('full_time', 'Full time')], default='', max_length=20),
        ),
    ]
